version: "3"

services:
  report-api:
    image: node:20.17-alpine
    working_dir: /src
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    networks:
      - existing
    command: sh -c "npm install && npm run dev"

networks:
  existing:
    name: sprint08-main
    external: true